#!/usr/bin/env bash
# Create the Flask configuration for the Deep Sec local-end-user lab.
set -euo pipefail

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
env_file="$script_dir/.env"
wallet_dir=${TNS_ADMIN:-${DB_WALLET_LOCATION:-$HOME/deep-sec-wallet/tns_admin}}
db_dsn=${DB_DSN:-deepsec_low}

say() {
  printf '\n==> %s\n' "$1"
}

dotenv_double_quote() {
  local value=$1
  value=${value//\\/\\\\}
  value=${value//\"/\\\"}
  value=${value//\$/\\$}
  printf '"%s"' "$value"
}

say 'Deep Sec Flask configuration'
echo "This script creates $env_file for the local-end-user web application."
echo "It does not collect or save Marvin's password."

[ -d "$wallet_dir" ] || { echo "ERROR: wallet directory not found: $wallet_dir" >&2; exit 1; }
for wallet_file in tnsnames.ora sqlnet.ora cwallet.sso; do
  [ -f "$wallet_dir/$wallet_file" ] || { echo "ERROR: $wallet_file is missing from $wallet_dir" >&2; exit 1; }
done
command -v openssl >/dev/null || { echo 'ERROR: openssl is required to generate FLASK_SECRET_KEY.' >&2; exit 1; }

say 'Wallet and database settings'
echo "Wallet directory: $wallet_dir"
echo "Database service alias: $db_dsn"
read -r -p "Use this database service alias [$db_dsn]: " entered_dsn
db_dsn=${entered_dsn:-$db_dsn}

echo 'The app uses Oracle Instant Client Thick mode and cwallet.sso.'
echo 'No wallet password is stored in .env.'

say 'Flask session protection'
flask_secret=$(openssl rand -hex 32)
echo 'Generated a new 64-character FLASK_SECRET_KEY with openssl rand -hex 32.'

if [ -f "$env_file" ]; then
  backup_file="$env_file.backup.$(date -u +%Y%m%dT%H%M%SZ)"
  say 'Existing configuration backup'
  cp -v "$env_file" "$backup_file"
fi

say 'Writing protected .env file'
umask 077
{
  printf '%s\n' '# Generated by configure_env.sh. Keep this file private.'
  printf '%s\n' 'FLASK_HOST=0.0.0.0'
  printf '%s\n' 'FLASK_PORT=7777'
  printf '%s\n' 'FLASK_DEBUG=false'
  printf 'FLASK_SECRET_KEY=%s\n' "$(dotenv_double_quote "$flask_secret")"
  printf '\n'
  printf 'DB_DSN=%s\n' "$(dotenv_double_quote "$db_dsn")"
  printf '%s\n' 'DB_SCHEMA=APPLAB'
  printf 'DB_WALLET_LOCATION=%s\n' "$(dotenv_double_quote "$wallet_dir")"
  printf '%s\n' 'DB_WALLET_PASSWORD='
} > "$env_file"
chmod 600 "$env_file"

say 'Configuration complete'
echo "Created: $env_file (mode 600)"
echo "DB_DSN: $db_dsn"
echo "DB_WALLET_LOCATION: $wallet_dir"
echo 'FLASK_SECRET_KEY: generated and stored without printing its value.'
echo 'Next: start the web server with ./run.sh'
