-- Run as an ADB administrator, read-only, changes nothing.
SELECT DATA_ROLE AS ROLE_NAME, MAPPED_TO, ENABLED_BY_DEFAULT FROM DBA_DATA_ROLES;
SELECT GRANT_NAME, PRIVILEGE, COLUMN_NAME, GRANTEE FROM DBA_DATA_GRANTS WHERE OBJECT_OWNER = 'APPLAB';
SELECT DISTINCT GRANT_NAME, PREDICATE FROM DBA_DATA_GRANTS WHERE OBJECT_OWNER = 'APPLAB';

WITH GRANTS AS (
  SELECT DISTINCT GRANT_NAME, OBJECT_NAME FROM DBA_DATA_GRANTS WHERE OBJECT_OWNER = 'APPLAB'
), OBJ_COLS AS (
  SELECT TABLE_NAME AS OBJECT_NAME, COLUMN_NAME, COLUMN_ID FROM ALL_TAB_COLUMNS WHERE OWNER = 'APPLAB'
), GRANT_PRIV AS (
  SELECT G.GRANT_NAME, G.OBJECT_NAME, G.PRIVILEGE, C.COLUMN_NAME FROM DBA_DATA_GRANTS G JOIN OBJ_COLS C ON C.OBJECT_NAME = G.OBJECT_NAME AND (G.COLUMN_NAME = C.COLUMN_NAME OR G.COLUMN_NAME IS NULL) WHERE G.OBJECT_OWNER = 'APPLAB' AND G.PRIVILEGE IN ('SELECT', 'UPDATE')
), GRANT_DELETE AS (
  SELECT DISTINCT GRANT_NAME, OBJECT_NAME FROM DBA_DATA_GRANTS WHERE OBJECT_OWNER = 'APPLAB' AND PRIVILEGE = 'DELETE'
)
SELECT GR.GRANT_NAME, GR.OBJECT_NAME,
       (SELECT COUNT(*) FROM OBJ_COLS OC2 WHERE OC2.OBJECT_NAME = GR.OBJECT_NAME) AS TOTAL_COLUMNS,
       COUNT(DISTINCT CASE WHEN GP.PRIVILEGE = 'SELECT' THEN GP.COLUMN_NAME END) AS SELECT_COLUMNS,
       COUNT(DISTINCT CASE WHEN GP.PRIVILEGE = 'UPDATE' THEN GP.COLUMN_NAME END) AS UPDATE_COLUMNS,
       CASE WHEN GD.GRANT_NAME IS NOT NULL THEN 'YES' ELSE 'NO' END AS CAN_DELETE
  FROM GRANTS GR LEFT JOIN GRANT_PRIV GP ON GP.GRANT_NAME = GR.GRANT_NAME LEFT JOIN GRANT_DELETE GD ON GD.GRANT_NAME = GR.GRANT_NAME
 GROUP BY GR.GRANT_NAME, GR.OBJECT_NAME, GD.GRANT_NAME ORDER BY GR.OBJECT_NAME, GR.GRANT_NAME;

WITH GRANTS AS (
  SELECT DISTINCT GRANT_NAME, OBJECT_NAME FROM DBA_DATA_GRANTS WHERE OBJECT_OWNER = 'APPLAB'
), OBJ_COLS AS (
  SELECT TABLE_NAME AS OBJECT_NAME, COLUMN_NAME, COLUMN_ID FROM ALL_TAB_COLUMNS WHERE OWNER = 'APPLAB'
), GRANT_PRIV AS (
  SELECT G.GRANT_NAME, G.OBJECT_NAME, G.PRIVILEGE, C.COLUMN_NAME FROM DBA_DATA_GRANTS G JOIN OBJ_COLS C ON C.OBJECT_NAME = G.OBJECT_NAME AND (G.COLUMN_NAME = C.COLUMN_NAME OR G.COLUMN_NAME IS NULL) WHERE G.OBJECT_OWNER = 'APPLAB' AND G.PRIVILEGE IN ('SELECT', 'UPDATE')
), GRANT_DELETE AS (
  SELECT DISTINCT GRANT_NAME, OBJECT_NAME FROM DBA_DATA_GRANTS WHERE OBJECT_OWNER = 'APPLAB' AND PRIVILEGE = 'DELETE'
)
SELECT GR.GRANT_NAME, GR.OBJECT_NAME, OC.COLUMN_NAME,
       CASE WHEN MAX(CASE WHEN GP.PRIVILEGE = 'SELECT' AND GP.COLUMN_NAME = OC.COLUMN_NAME THEN 1 END) = 1 THEN 'YES' ELSE 'NO' END AS CAN_SELECT,
       CASE WHEN MAX(CASE WHEN GP.PRIVILEGE = 'UPDATE' AND GP.COLUMN_NAME = OC.COLUMN_NAME THEN 1 END) = 1 THEN 'YES' ELSE 'NO' END AS CAN_UPDATE,
       CASE WHEN GD.GRANT_NAME IS NOT NULL THEN 'YES' ELSE 'NO' END AS CAN_DELETE
  FROM GRANTS GR JOIN OBJ_COLS OC ON OC.OBJECT_NAME = GR.OBJECT_NAME LEFT JOIN GRANT_PRIV GP ON GP.GRANT_NAME = GR.GRANT_NAME AND GP.COLUMN_NAME = OC.COLUMN_NAME LEFT JOIN GRANT_DELETE GD ON GD.GRANT_NAME = GR.GRANT_NAME
 GROUP BY GR.GRANT_NAME, GR.OBJECT_NAME, OC.COLUMN_NAME, OC.COLUMN_ID, GD.GRANT_NAME ORDER BY GR.OBJECT_NAME, GR.GRANT_NAME, OC.COLUMN_ID;

SELECT ROLE_TYPE, DATA_ROLE AS ROLE_NAME, GRANTEE, GRANTEE_TYPE FROM DBA_DATA_ROLE_GRANTS ORDER BY ROLE_TYPE, DATA_ROLE, GRANTEE;
SELECT USERNAME, ACCOUNT_STATUS, CREATED_DATE FROM DBA_END_USERS;
SELECT CONTEXT_OWNER, CONTEXT_NAME, HANDLER_PACKAGE, HANDLER_PROCEDURE, HANDLER_STATUS FROM DBA_END_USER_CONTEXT_DEFINITIONS WHERE CONTEXT_OWNER = 'APPLAB';
