-- Run as an ADB administrator, read-only, changes nothing.
SELECT DATA_ROLE AS ROLE_NAME, MAPPED_TO, ENABLED_BY_DEFAULT FROM DBA_DATA_ROLES;
SELECT GRANT_NAME, PRIVILEGE, COLUMN_NAME, GRANTEE FROM DBA_DATA_GRANTS WHERE OBJECT_OWNER = 'APPLAB';
SELECT DISTINCT GRANT_NAME, PREDICATE FROM DBA_DATA_GRANTS WHERE OBJECT_OWNER = 'APPLAB';
SELECT ROLE_TYPE, DATA_ROLE AS ROLE_NAME, GRANTEE, GRANTEE_TYPE FROM DBA_DATA_ROLE_GRANTS ORDER BY ROLE_TYPE, DATA_ROLE, GRANTEE;
SELECT USERNAME, ACCOUNT_STATUS, CREATED_DATE FROM DBA_END_USERS;
SELECT CONTEXT_OWNER, CONTEXT_NAME, HANDLER_PACKAGE, HANDLER_PROCEDURE, HANDLER_STATUS FROM DBA_END_USER_CONTEXT_DEFINITIONS WHERE CONTEXT_OWNER = 'APPLAB';
